### PR TITLE
Add dco for Andrew Wyllie. covered by: goldmans_sachs-andrew_wyllie.dco

### PR DESCRIPTION
**Pull request by AndrewWyllie**
Hi there,

I'd like to add my DCO so I can contribute to Reladomo please.

FYI I am working on a bug fix for a race condition in deep fetch, which I'll submit a separate pull request for when it is ready.

Thanks,
Andrew

### CODE REVIEW

**Comment by AndrewWyllie** [comment]
Seems the build is broken due to some recent travis upgrade. Trying to check for any obvious solution but help would be welcome.

**Comment by mohrezaei** [comment]
Technically, as a GS employee, you don't need a DCO (it's optional). The build problem is a bigger issue. The only workaround I found is here:
https://github.com/mybatis/mybatis-3/pull/1452/files
Can you try that?

**Comment by AndrewWyllie** [comment]
Hi Moh,

I've updated my branch with the fix for the build problem.

It took a fair bit of experimentation to find the solution but in the end it was straightforward. The key was that the jdk: tag was causing the install-jdk.sh error as apparently this jdk: tag controls the native Travis java integration which does not support Java 6 anymore. Once that was removed the apt install successfully installed the openjdk6 package but I could see the build was actually running Java 8 and it failed with compilation errors. Hence added 'jdk_switcher use openjdk6' which updates JAVA_HOME to the correct path and now the build succeeds.

Let me know if this looks good to merge.

Thanks,
Andrew

**Comment by mohrezaei** [comment]
Already merged :smile: thanks for the fix.

**Comment by AndrewWyllie** [comment]
Fantastic - thanks. Will let you know about the deep fetch fix. Hoping to have it ready next week.

**Pull request merged**
