### PR TITLE
Fix Or Operation on partial cached results

### PR DESCRIPTION
**Pull request by vborisoff**
The method ignored the  partialResult from the first Operation

### CODE REVIEW

**Comment by mohrezaei** [comment]
Please add a test case.

**Comment by vborisoff** [comment]
absolutely
will add tomorrow.

**Comment by mohrezaei** [comment]
The test is not properly setup because it extends `MithraTestResource`. Additionally, the test case doesn't run in both Partial an Full cache modes.

There is a class called `TestOr`. Like the existing tests, it loads data from `mithraTestDataDefaultSource.txt`, which should have enough data for your test.

Here is a patch that works:
```
Index: reladomo/src/main/java/com/gs/fw/common/mithra/finder/OrOperation.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- reladomo/src/main/java/com/gs/fw/common/mithra/finder/OrOperation.java	(revision 79d69e56bbe321d106e4edea1c332123ac06763d)
+++ reladomo/src/main/java/com/gs/fw/common/mithra/finder/OrOperation.java	(date 1540524793662)
@@ -257,6 +257,8 @@
             return null;
         }
         FullUniqueIndex result = new FullUniqueIndex(ExtractorBasedHashStrategy.IDENTITY_HASH_STRATEGY);
+        result.addAll(partialResult);
+
         for (int i = 1; i < operations.length; i++)
         {
             partialResult = operation.getResultObjectPortal().zFindInMemoryWithoutAnalysis(operations[i], true);
Index: reladomo/src/test/java/com/gs/fw/common/mithra/test/TestSqlDatatypes.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- reladomo/src/test/java/com/gs/fw/common/mithra/test/TestSqlDatatypes.java	(revision 79d69e56bbe321d106e4edea1c332123ac06763d)
+++ reladomo/src/test/java/com/gs/fw/common/mithra/test/TestSqlDatatypes.java	(date 1540524575208)
@@ -68,6 +68,7 @@
             OrderStatusWi.class,
             Product.class,
             ProductSynonym.class,
+            DatedEntity.class,
             UserGroup.class,
             BigOrder.class,
             BigOrderItem.class
Index: reladomo/src/test/java/com/gs/fw/common/mithra/test/TestOr.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- reladomo/src/test/java/com/gs/fw/common/mithra/test/TestOr.java	(revision 79d69e56bbe321d106e4edea1c332123ac06763d)
+++ reladomo/src/test/java/com/gs/fw/common/mithra/test/TestOr.java	(date 1540524618926)
@@ -26,6 +26,7 @@
 import com.gs.fw.common.mithra.test.domain.OrderStatus;
 import com.gs.fw.common.mithra.test.domain.ParaDeskFinder;
 import com.gs.fw.common.mithra.test.domain.ParaDeskList;
+import com.gs.fw.common.mithra.test.domain.DatedEntityFinder;
 import org.eclipse.collections.impl.set.mutable.primitive.IntHashSet;
 
 import java.sql.SQLException;
@@ -59,6 +60,19 @@
         OrderFinder.findMany(op).forceResolve();
     }
 
+    public void testPartialCombine()
+    {
+        com.gs.fw.finder.Operation procOp = DatedEntityFinder.processingDate ().eq (Timestamp.valueOf ("2017-10-30 23:59:00"));
+
+        com.gs.fw.finder.Operation op1 = DatedEntityFinder.id ().eq (1);
+        com.gs.fw.finder.Operation op2 = DatedEntityFinder.id ().greaterThan (2);
+
+        assertEquals (1, DatedEntityFinder.findMany (op1.and(procOp)).size());
+        assertEquals (8, DatedEntityFinder.findMany (op2.and(procOp)).size());
+
+        assertEquals (9, DatedEntityFinder.findMany (op1.and(procOp).or(op2.and(procOp))).size());
+    }
+
     public void testOuterJoinLikeOr()
     {
         Operation op = OrderFinder.description().startsWith("S").or(OrderFinder.orderStatus().status().notEq(10));

```

**Comment by mohrezaei** [comment]
looks like you've mixed in other commits in this branch! Please use separate branches, as Github automatically pulls in all commits when you create a pull request.

The `OrOperation` changes look good.

**Pull request closed without merging**
